name: schedule_fetcher

on:
  schedule:
    - cron: '0 6 */1 * *'

  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
      
    - name: wget
      uses: wei/wget@v1
      with:
        args: -O resp.json https://chii.ai/api/subjects/ranking
    - name: shrink
      run: python3 shrink.py
      
    - uses: stefanzweifel/git-auto-commit-action@v4
