name: schedule_fetcher

on:
  schedule:
    - cron: '45 * * * *'

  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
    
    - name: get-raw-json
      id: myRequest
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://chii.ai/api/subjects/ranking'
        method: 'GET'
        customHeaders: '{"Content-Type": "application/json"}'
    - name: echo-resp
      run: echo ${{ steps.myRequest.outputs.response }} > resp.json
      
    - uses: stefanzweifel/git-auto-commit-action@v4
